steps:
  - name: gcr.io/cloud-builders/docker
    id: Build
    args:
      - build
      - '-t'
      - 'gcr.io/$PROJECT_ID/production:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/production:latest'
      - .
      - '-f'
      - Dockerfile

  - name: gcr.io/cloud-builders/docker
    id: Push
    args:
      - push
      - 'gcr.io/$PROJECT_ID/production:$COMMIT_SHA'

  - name: gcr.io/cloud-builders/docker
    id: Push Latest
    args:
      - push
      - 'gcr.io/$PROJECT_ID/production:latest'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: Deploy
    args:
      - run
      - services
      - update
      - production
      - '--platform=managed'
      - '--image=gcr.io/$PROJECT_ID/production:$COMMIT_SHA'
      - '--region=australia-southeast1'
      - '--add-cloudsql-instances=gd-ndis-healthcheck:australia-southeast1:gd-ndis-healthcheck'
      - '--timeout=600'
      - '--quiet'
    entrypoint: gcloud

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: Update Migration Job Image
    args:
      - run
      - jobs
      - update
      - portal-migrate
      - '--image=gcr.io/$PROJECT_ID/production:$COMMIT_SHA'
      - '--region=australia-southeast1'
    entrypoint: gcloud

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: Run Migrations
    args:
      - run
      - jobs
      - execute
      - portal-migrate
      - '--region=australia-southeast1'
      - '--wait'
    entrypoint: gcloud

images:
  - 'gcr.io/$PROJECT_ID/production:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/production:latest'

options:
  logging: CLOUD_LOGGING_ONLY
